---
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago.
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure packages from install_deps.sh are installed.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
  with_items: ""{{ deps_packages }}"

- name: Set python3 as the default python alternative
  community.general.alternatives:
    name: python3
    path: /usr/bin/python3.11
    link: /usr/bin/python3
    state: present

- name: Create .gnupg folder.
  ansible.builtin.file:
    path: /root/.gnupg
    state: directory
    owner: root
    group: root
    mode: 0600

- name: Install Coral Runtime.
  ansible.builtin.apt:
    deb: "https://github.com/feranick/libedgetpu/releases/download/16.0TF2.17.1-1/libedgetpu1-max_16.0tf2.17.1-1.bookworm_{{ dpkg_arch }}.deb"

- name: Add specified repository into sources list using specified filename
  ansible.builtin.apt_repository:
    repo: deb http://dl.google.com/linux/chrome/deb/ stable main
    state: present
    filename: google-chrome

- name: Add mesa-teflon-delegate from bookworm-backports 1/2.
  block:
    - name: Add mesa-teflon-delegate from bookworm-backports 1/2.
      ansible.builtin.apt_repository:
        repo: deb http://deb.debian.org/debian bookworm-backports main
        state: present
        filename: bookworm-backbacks

    - name: Add mesa-teflon-delegate from bookworm-backports 2/2.
      ansible.builtin.apt:
        name: "mesa-teflon-delegate/bookworm-backports"
        state: present
        install_recommends: false
        install_suggests: false

- name: Install ffmpeg.
  block:
    - name: Create folder for 5.0 version.
      ansible.builtin.file:
        path: /usr/lib/ffmpeg/5.0
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Create folder for 7.0 version.
      ansible.builtin.file:
        path: /usr/lib/ffmpeg/7.0
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Unarchive 5.0 version.
      ansible.builtin.unarchive:
        src: https://github.com/NickM-27/FFmpeg-Builds/releases/download/autobuild-2022-07-31-12-37/ffmpeg-n5.1-2-g915ef932a3-linux64-gpl-5.1.tar.xz
        dest: /usr/lib/ffmpeg/5.0
        remote_src: true
        extra_opts:
          - --strip-components
          - 1
          - amd64/bin/ffmpeg
          -  amd64/bin/ffprobe

    - name: Unarchive 7.0 version.
      ansible.builtin.unarchive:
        src: https://github.com/NickM-27/FFmpeg-Builds/releases/download/autobuild-2024-09-19-12-51/ffmpeg-n7.0.2-18-g3e6cec1286-linux64-gpl-7.0.tar.xz
        dest: /usr/lib/ffmpeg/7.0
        remote_src: true
        extra_opts:
          - --strip-components
          - 1
          - amd64/bin/ffmpeg
          -  amd64/bin/ffprobe

- name: Install non-free of i965 driver.
  block:
    - name: Change source list debian.sources 1/2.
      ansible.builtin.lineinfile:
        path: etc/apt/sources.list.d/debian.sources
        regexp: "^Components: main$"
        line: Components: main contrib non-free non-free-firmware

    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes

    - name: Install i965 driver.
      ansible.builtin.apt:
        name: i965-va-driver-shaders
        state: present
        install_recommends: false
        install_suggests: false

    - name: Revert changes source list debian.sources 2/2.
      ansible.builtin.lineinfile:
        path: etc/apt/sources.list.d/debian.sources
        regexp: "^Components: main contrib non-free non-free-firmware$"
        line: "Components: main"

    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes

    - name: Install intel-i965 drivers.
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        install_recommends: false
      with_items:
        - intel-gpu-tools
        - onevpl-tools
        - libva-drm2
        - mesa-va-drivers
        - radeontop

    - name: Update dpkg package.
      ansible.builtin.apt:
        name: dpkg
        state: latest

- name: Install intel-i965 drivers.
  block:
    - name: Ensure that folder exists.
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        owner: root
        group: root
        mode: 0755

    - name: Download the package signing key for the Intel Graphics repository
      ansible.builtin.get_url:
        url: https://repositories.intel.com/gpu/intel-graphics.key
        dest: /tmp/intel-graphics.asc
        checksum: "sha256:d66737072e192f2f162cfb433cd0d680e6ef85d27c606a826ed7b3ebc22a92dc"

    - name: Dearmor the downloaded signing key file
      shell: gpg --batch --dearmor -o /usr/share/keyrings/intel-graphics.gpg /tmp/intel-graphics.asc
      args:
        creates: /usr/share/keyrings/intel-graphics.gpg

    - name: Add Intel Graphics repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jammy client"
        state: present
        filename: intel-gpu-jammy

    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes

    - name: Install intel packages 1/3.
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        install_recommends: false
      with_items:
        - intel-media-va-driver-non-free
        - libmfx1
        - libmfxgen1
        - libvpl2

    - name: Install intel packages 2/3.
      ansible.builtin.apt:
        name: ocl-icd-libopencl1
        state: present
      
    - name: Install intel packages 3/3.
      ansible.builtin.apt:
        name: libtbb12
        state: present

    - name: Remove Intel Graphics repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/intel-graphics.gpg] https://repositories.intel.com/gpu/ubuntu jammy client"
        state: absent
        filename: intel-gpu-jammy

    - name: Install legacy packages.
      ansible.builtin.apt:
        deb: "{{ item }}"
        state: present
      with_items:
        - https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/libigdgmm12_22.5.5_amd64.deb
        - https://github.com/intel/compute-runtime/releases/download/24.35.30872.36/intel-opencl-icd-legacy1_24.35.30872.36_amd64.deb
        - https://github.com/intel/compute-runtime/releases/download/24.35.30872.36/intel-level-zero-gpu-legacy1_1.5.30872.36_amd64.deb
        - https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.17537.24/intel-igc-opencl_1.0.17537.24_amd64.deb
        - https://github.com/intel/intel-graphics-compiler/releases/download/igc-1.0.17537.24/intel-igc-core_1.0.17537.24_amd64.deb
        - https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/intel-opencl-icd_24.52.32224.5_amd64.deb
        - https://github.com/intel/compute-runtime/releases/download/24.52.32224.5/intel-level-zero-gpu_1.6.32224.5_amd64.deb
        - https://github.com/intel/intel-graphics-compiler/releases/download/v2.5.6/intel-igc-opencl-2_2.5.6+18417_amd64.deb
        - https://github.com/intel/intel-graphics-compiler/releases/download/v2.5.6/intel-igc-core-2_2.5.6+18417_amd64.deb
        - https://github.com/oneapi-src/level-zero/releases/download/v1.21.9/level-zero_1.21.9+u22.04_amd64.deb
        - https://github.com/intel/linux-npu-driver/releases/download/v1.17.0/intel-driver-compiler-npu_1.17.0.20250508-14912879441_ubuntu22.04_amd64.deb
        - https://github.com/intel/linux-npu-driver/releases/download/v1.17.0/intel-fw-npu_1.17.0.20250508-14912879441_ubuntu22.04_amd64.deb
        - https://github.com/intel/linux-npu-driver/releases/download/v1.17.0/intel-level-zero-npu_1.17.0.20250508-14912879441_ubuntu22.04_amd64.deb

- name: Install Vulcan drivers.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    install_recommends: false
  with_items:
    - libvulkan1
    - mesa-vulkan-drivers

- name: Purge packages.
  ansible.builtin.apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - gnupg
    - apt-transport-https
    - xz-utils

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes

- name: Download the package signing key for the Intel Graphics repository
  ansible.builtin.get_url:
    url: "https://github.com/mikefarah/yq/releases/download/v4.48.2/yq_linux_{{ dpkg_arch }}"
    dest: /usr/local/bin/yq
    checksum: "sha256:0ffc35320180d4911bc3a772934da508715e08af444cb33d4d43660065e25bcc"
    owner: root
    group: root
    mode: 0755

