---
- name: Ensure that folders are exist.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  with_items:
    - /opt/frigate
    - /command
    - /package
    - /etc/s6-overlay/s6-rc.d
    - /openvino-model
    - /labelmap

- name: Rsync files /usr/local.
  ansible.builtin.command:
    cmd: "rsync -avz /home/support/barefrigate/frigate/usr/local/ /usr/local/"
  register: _rc
  failed_when: _rc.rc != 0

- name: Copy files to /opt/frigate.
  ansible.builtin.command:
    cmd: "rsync -avz /home/support/barefrigate/frigate/opt/frigate/ /opt/frigate/"
  register: _rc
  failed_when: _rc.rc != 0

- name: Copy files to /command.
  ansible.builtin.command:
    cmd: "rsync -avz /home/support/barefrigate/frigate/command/ /command/"
  register: _rc
  failed_when: _rc.rc != 0

- name: Copy files to /package.
  ansible.builtin.command:
    cmd: "rsync -avz /home/support/barefrigate/frigate/package/ /package/"
  register: _rc
  failed_when: _rc.rc != 0

- name: Copy files to /etc/s6-overlay/s6-rc.d.
  ansible.builtin.command:
    cmd: "rsync -avz /home/support/barefrigate/frigate/etc/s6-overlay/s6-rc.d/ /etc/s6-overlay/s6-rc.d/"
  register: _rc
  failed_when: _rc.rc != 0

- name: Copy files to /openvino-models.
  ansible.builtin.command:
    cmd: "rsync -avz /home/support/barefrigate/frigate/openvino-model/ /openvino-model/"
  register: _rc
  failed_when: _rc.rc != 0

- name: Copy files to /labelmap.
  ansible.builtin.command:
    cmd: "rsync -avz /home/support/barefrigate/frigate/labelmap/ /labelmap/"
  register: _rc
  failed_when: _rc.rc != 0

- name: Copy files to /.
  ansible.builtin.command:
    cmd: "cp /home/support/barefrigate/frigate/{{ item }} /"
  register: _rc
  failed_when: _rc.rc != 0
  with_items:
    - audio-labelmap.txt
    - cpu_audio_model.tflite
    - cpu_model.tflite
    - edgetpu_model.tflite
    - get-pip.py
    - init
    - labelmap.txt
