---
- name: Set environment variables.
  ansible.builtin.lineinfile:
    path: "/etc/environment"
    state: present
    regexp: "^{{ item.name }}"
    line: "{{ item.name }}={{ item.value }}"
  with_items: "{{ envs }}"
