---
- name: Do bare frigate.
  hosts: frigate
  gather_facts: true
  become: true

  vars_files:
  - vars.yaml

  handlers:
  - name: Daemon-reload
    ansible.builtin.systemd:
      daemon_reload: true

  - name: Frigate-config-mount-enabled
    ansible.builtin.systemd:
      name: config.mount
      enabled: true

  - name: Frigate-db-mount-enabled
    ansible.builtin.systemd:
      name: db.mount
      enabled: true

  - name: Frigate-storage-mount-enabled
    ansible.builtin.systemd:
      name: media-frigate.mount
      enabled: true

  - name: Frigate-config-mount-started
    ansible.builtin.systemd:
      name: config.mount
      state: started

  - name: Frigate-db-mount-started
    ansible.builtin.systemd:
      name: db.mount
      state: started

  - name: Frigate-storage-mount-started
    ansible.builtin.systemd:
      name: media-frigate.mount
      state: started

  - name: Target-frigate-restarted
    ansible.builtin.systemd:
      name: frigate.target
      state: restarted
      enabled: true

  - name: Target-frigate-started
    ansible.builtin.systemd:
      name: frigate.target
      state: started
      enabled: true

  - name: Service-create-logs-restarted
    ansible.builtin.systemd:
      name: create-logs.service
      state: restarted
      enabled: true

  - name: Service-create-logs-started
    ansible.builtin.systemd:
      name: create-logs.service
      state: started
      enabled: true

  - name: Service-certsync-restarted
    ansible.builtin.systemd:
      name: certsync.service
      state: restarted
      enabled: true

  - name: Service-certsync-started
    ansible.builtin.systemd:
      name: certsync.service
      state: started
      enabled: true

  - name: Service-frigate-restarted
    ansible.builtin.systemd:
      name: frigate.service
      state: restarted
      enabled: true

  - name: Service-frigate-started
    ansible.builtin.systemd:
      name: frigate.service
      state: started
      enabled: true

  - name: Service-go2rtc-restarted
    ansible.builtin.systemd:
      name: go2rtc.service
      state: restarted
      enabled: true

  - name: Service-go2rtc-started
    ansible.builtin.systemd:
      name: go2rtc.service
      state: started
      enabled: true

  - name: Service-nginx-restarted
    ansible.builtin.systemd:
      name: nginx.service
      state: restarted
      enabled: true

  - name: Service-nginx-started
    ansible.builtin.systemd:
      name: nginx.service
      state: started
      enabled: true

  tasks:
  - name: Fail if.
    ansible.builtin.include_tasks: fail.yaml

  - name: Do apt install.
    ansible.builtin.include_tasks: apt.yaml

  - name: Copy files to remote server.
    ansible.builtin.include_tasks: copy-files.yaml

#  - name: Create and install systemd services.
#    ansible.builtin.include_tasks: systemd.yaml

  - name: Set Environment variables.
    ansible.builtin.include_tasks: envs.yaml

  - name: Update systemd units.
    ansible.builtin.include_tasks: systemd.yaml

  - name: Update s6 files.
    ansible.builtin.include_tasks: s6.yaml

  - name: Update nginx.conf.
    ansible.builtin.include_tasks: nginx.yaml

  - name: Create or update frigate config file.
    ansible.builtin.include_tasks: frigate-config.yaml

#  - name: Create systemd mounts.
#    ansible.builtin.include_tasks: systemd-mounts.yaml

  - name: Disable unattended upgrades.
    ansible.builtin.include_tasks: disable-unattended-upgrades.yaml
