---
- name: Create or update systemd target file.
  ansible.builtin.template:
    src: ./templates/systemd/frigate.target
    dest: /etc/systemd/system/frigate.target
    owner: root
    group: root
    mode: '0644'
  notify:
    - Daemon-reload
    - Target-frigate-started
    - Target-frigate-restarted

- name: Create or update systemd unit files.
  ansible.builtin.template:
    src: "./templates/systemd/{{ item }}.service"
    dest: "/etc/systemd/system/{{ item }}.service"
    owner: root
    group: root
    mode: '0644'
  notify:
    - Daemon-reload
    - "Service-{{ item }}-restarted"
    - "Service-{{ item }}-started"
  with_items:
    - certsync
    - frigate
    - go2rtc
    - nginx
    - create-logs

- name: Create pre-frigate.sh.
  ansible.builtin.template:
    src: ./templates/frigate/pre-frigate.sh
    dest: /usr/local/bin/pre-frigate.sh
    owner: root
    group: root
    mode: '0755'
  notify:
    - Service-frigate-restarted
    - Service-frigate-started
